[tool.poetry]
name = "your-project-name"  # Replace with your actual project name
version = "0.1.0"          # Semantic version (e.g., 0.1.0)
description = "Your project description"
authors = ["Your Name <your.email@example.com>"]
license = "MIT"  # Optional but recommended